# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6abcaa4c167661354102c70c0064fbe0897cfffda3125255f1fe499fbfa0e44f3262198861da616ba2e2601e16d2102878ced3bb00cbf0f97c3b4680bdc83ee

test:
  secret_key_base: d18fba18f7f73228c0cd7815a981c41b3059ab93107dc99c439137ffd52fcdd1d13eb1eab89c843d7722887d1ada2ea7de67cc90c5217a75c2c1f2e61ea5a524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
